name: PHPunit

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          tools: composer, phpunit

      - name: Composer Update
        run: |
          composer update

      - name: Unit Test
        run: |
          ./vendor/bin/phpunit
